In [22]:
import pandas as pd

# Load all datasets
transaction = pd.read_excel(r"C:\Users\kisho\Downloads\Tourism_Experience_Analytics_Project\Data\Transaction.xlsx")
mode = pd.read_excel(r"C:\Users\kisho\Downloads\Tourism_Experience_Analytics_Project\Data\Mode.xlsx")
country = pd.read_excel(r"C:\Users\kisho\Downloads\Tourism_Experience_Analytics_Project\Data\Country.xlsx")
type_df = pd.read_excel(r"C:\Users\kisho\Downloads\Tourism_Experience_Analytics_Project\Data\Type.xlsx")
continent = pd.read_excel(r"C:\Users\kisho\Downloads\Tourism_Experience_Analytics_Project\Data\Continent.xlsx")
region = pd.read_excel(r"C:\Users\kisho\Downloads\Tourism_Experience_Analytics_Project\Data\Region.xlsx")
user = pd.read_excel(r"C:\Users\kisho\Downloads\Tourism_Experience_Analytics_Project\Data\User.xlsx")
city = pd.read_excel(r"C:\Users\kisho\Downloads\Tourism_Experience_Analytics_Project\Data\City.xlsx")
item = pd.read_excel(r"C:\Users\kisho\Downloads\Tourism_Experience_Analytics_Project\Data\Item.xlsx")
updated_item = pd.read_excel(r"C:\Users\kisho\Downloads\Tourism_Experience_Analytics_Project\Data\Additional_Data_for_Attraction_Sites\Updated_Item.xlsx")

# Print basic info
datasets = {
    "Transaction": transaction,
    "Mode": mode,
    "Country": country,
    "Type": type_df,
    "Continent": continent,
    "Region": region,
    "User": user,
    "City": city,
    "Item": item,
    "Updated_Item": updated_item
}

for name, df in datasets.items():
    print(f"\n{name} Dataset Shape: {df.shape}")
    print(df.head())


for name, df in datasets.items():
    print(f"\n{name} Info:")
    print(df.info())




Transaction Dataset Shape: (52930, 7)
   TransactionId  UserId  VisitYear  VisitMonth  VisitMode  AttractionId  \
0              3   70456       2022          10          2           640   
1              8    7567       2022          10          4           640   
2              9   79069       2022          10          3           640   
3             10   31019       2022          10          3           640   
4             15   43611       2022          10          2           640   

   Rating  
0       5  
1       5  
2       5  
3       3  
4       3  

Mode Dataset Shape: (6, 2)
   VisitModeId VisitMode
0            0         -
1            1  Business
2            2   Couples
3            3    Family
4            4   Friends

Country Dataset Shape: (165, 3)
   CountryId   Country  RegionId
0          0         -         0
1          1  Cameroon         1
2          2      Chad         1
3          3    Rwanda         1
4          4  Ethiopia         2

Type Dataset Shape: (1

In [23]:
for name, df in datasets.items():
    print(f"\n{name} Missing Values:")
    print(df.isnull().sum())



Transaction Missing Values:
TransactionId    0
UserId           0
VisitYear        0
VisitMonth       0
VisitMode        0
AttractionId     0
Rating           0
dtype: int64

Mode Missing Values:
VisitModeId    0
VisitMode      0
dtype: int64

Country Missing Values:
CountryId    0
Country      0
RegionId     0
dtype: int64

Type Missing Values:
AttractionTypeId    0
AttractionType      0
dtype: int64

Continent Missing Values:
ContinentId    0
Continent      0
dtype: int64

Region Missing Values:
Region         0
RegionId       0
ContinentId    0
dtype: int64

User Missing Values:
UserId         0
ContinentId    0
RegionId       0
CountryId      0
CityId         4
dtype: int64

City Missing Values:
CityId       0
CityName     1
CountryId    0
dtype: int64

Item Missing Values:
AttractionId         0
AttractionCityId     0
AttractionTypeId     0
Attraction           0
AttractionAddress    0
dtype: int64

Updated_Item Missing Values:
AttractionId         0
AttractionCityId     0
Attrac

In [24]:
transaction.describe()


,TransactionId,UserId,VisitYear,VisitMonth,VisitMode,AttractionId,Rating
count,52930.000000,52930.000000,52930.000000,52930.000000,52930.000000,52930.000000,52930.000000
mean,70415.130474,45024.522596,2016.351899,6.633100,2.945759,759.663782,4.157699
std,66299.514206,25073.062199,1.732926,3.392979,1.000683,210.716111,0.970543
min,3.000000,14.000000,2013.000000,1.000000,1.000000,369.000000,1.000000
25%,19646.250000,23470.000000,2015.000000,4.000000,2.000000,640.000000,4.000000
50%,42770.500000,45533.500000,2016.000000,7.000000,3.000000,737.000000,4.000000
75%,105638.750000,66667.000000,2018.000000,9.000000,4.000000,841.000000,5.000000
max,211241.000000,88190.000000,2022.000000,12.000000,5.000000,1297.000000,5.000000


In [25]:
transaction['Rating'].unique()


array([5, 3, 4, 1, 2])

In [26]:
transaction['VisitMonth'].unique()


array([10,  9,  8,  7,  6,  5,  4, 11,  1, 12,  3,  2])

In [27]:
transaction['VisitYear'].unique()


array([2022, 2021, 2020, 2019, 2018, 2014, 2013, 2017, 2016, 2015])

In [28]:
transaction.drop_duplicates(inplace=True)


In [29]:
user.duplicated().sum()

user.isnull().sum()



UserId         0
ContinentId    0
RegionId       0
CountryId      0
CityId         4
dtype: int64

In [30]:
user['UserId'].nunique()


33530

In [31]:
updated_item['AttractionId'].nunique()


1698

In [32]:
print(item.shape)
print(updated_item.shape)


(30, 5)
(1698, 5)


In [33]:
print(item.columns)
print(updated_item.columns)


Index(['AttractionId', 'AttractionCityId', 'AttractionTypeId', 'Attraction',
       'AttractionAddress'],
      dtype='object')
Index(['AttractionId', 'AttractionCityId', 'AttractionTypeId', 'Attraction',
       'AttractionAddress'],
      dtype='object')


In [34]:
# Remove users with missing CityId
user = user.dropna(subset=['CityId'])

# Convert to integer
user['CityId'] = user['CityId'].astype(int)




C:\Users\kisho\AppData\Local\Temp\ipykernel_26580\1863371530.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  user['CityId'] = user['CityId'].astype(int)


In [35]:
user.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33526 entries, 0 to 33529
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   UserId       33526 non-null  int64
 1   ContinentId  33526 non-null  int64
 2   RegionId     33526 non-null  int64
 3   CountryId    33526 non-null  int64
 4   CityId       33526 non-null  int64
dtypes: int64(5)
memory usage: 1.5 MB


In [36]:
(updated_item['AttractionCityId']==6879).any()


np.False_

In [37]:
city = city.dropna(subset=['CityName'])


In [38]:
city.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9142 entries, 0 to 9142
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   CityId     9142 non-null   int64 
 1   CityName   9142 non-null   object
 2   CountryId  9142 non-null   int64 
dtypes: int64(2), object(1)
memory usage: 285.7+ KB


In [39]:
updated_item['AttractionTypeId'].unique()

array([13, 63, 76, 72, 93, 92, 61, 64, 82, 91, 84, 19, 34, 10, 2, 45, 44,
       'Temple', 'Beach', 'Park', 'Museum', 'Market'], dtype=object)

In [40]:
mapping = {
    'Temple': 76,
    'Beach': 13,
    'Park': 61,
    'Museum': 45,
    'Market': 34
}


In [41]:
updated_item['AttractionTypeId'] = updated_item['AttractionTypeId'].replace(mapping)


C:\Users\kisho\AppData\Local\Temp\ipykernel_26580\33942238.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  updated_item['AttractionTypeId'] = updated_item['AttractionTypeId'].replace(mapping)


In [42]:
updated_item['AttractionTypeId'] = updated_item['AttractionTypeId'].astype(int)


In [43]:
updated_item.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1698 entries, 0 to 1697
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   AttractionId       1698 non-null   int64 
 1   AttractionCityId   1698 non-null   int64 
 2   AttractionTypeId   1698 non-null   int64 
 3   Attraction         1698 non-null   object
 4   AttractionAddress  1698 non-null   object
dtypes: int64(3), object(2)
memory usage: 66.5+ KB


In [44]:
# Check if all AttractionIds in Transaction exist in Updated_Item
transaction['AttractionId'].isin(updated_item['AttractionId']).all()


np.True_

In [45]:
# Check UserId consistency
print(transaction['UserId'].isin(user['UserId']).all())

# Check VisitModeId consistency
print(transaction['VisitMode'].isin(mode['VisitModeId']).all())

# Check AttractionId consistency
print(transaction['AttractionId'].isin(updated_item['AttractionId']).all())


False
True
True


In [46]:
user.shape

(33526, 5)

In [47]:
transaction.shape

(52930, 7)

In [48]:
transaction['VisitMode'].unique()

array([2, 4, 3, 5, 1])

In [49]:
invalid_users = transaction[~transaction['UserId'].isin(user['UserId'])]

print(invalid_users['UserId'].unique())
print("Number of problematic rows:", invalid_users.shape[0])


[ 7175 56972 17595 67461]
Number of problematic rows: 8


In [50]:
transaction = transaction[transaction['UserId'].isin(user['UserId'])]


In [51]:
print(transaction['UserId'].isin(user['UserId']).all())


True


In [52]:
transaction.shape

(52922, 7)

In [53]:
transaction.info()

<class 'pandas.core.frame.DataFrame'>
Index: 52922 entries, 0 to 52929
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TransactionId  52922 non-null  int64
 1   UserId         52922 non-null  int64
 2   VisitYear      52922 non-null  int64
 3   VisitMonth     52922 non-null  int64
 4   VisitMode      52922 non-null  int64
 5   AttractionId   52922 non-null  int64
 6   Rating         52922 non-null  int64
dtypes: int64(7)
memory usage: 3.2 MB


In [54]:
transaction = transaction.rename(columns={'VisitMode': 'VisitModeId'})



In [55]:
transaction.info()

<class 'pandas.core.frame.DataFrame'>
Index: 52922 entries, 0 to 52929
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TransactionId  52922 non-null  int64
 1   UserId         52922 non-null  int64
 2   VisitYear      52922 non-null  int64
 3   VisitMonth     52922 non-null  int64
 4   VisitModeId    52922 non-null  int64
 5   AttractionId   52922 non-null  int64
 6   Rating         52922 non-null  int64
dtypes: int64(7)
memory usage: 3.2 MB


In [73]:
master = transaction.copy()

# Merge user
master = master.merge(user, on='UserId', how='left')

# Merge mode
master = master.merge(mode, on='VisitModeId', how='left')

# Merge attraction
master = master.merge(updated_item, on='AttractionId', how='left')

# Merge attraction type
master = master.merge(type_df, on='AttractionTypeId', how='left')

# Merge City (ONLY CityName)
master = master.merge(
    city[['CityId', 'CityName']],
    on='CityId',
    how='left'
)

# Merge Country (ONLY Country Name)
master = master.merge(
    country[['CountryId', 'Country']],
    on='CountryId',
    how='left'
)

# Merge Region (ONLY Region Name)
master = master.merge(
    region[['RegionId', 'Region']],
    on='RegionId',
    how='left'
)

# Merge Continent (ONLY Continent Name)
master = master.merge(
    continent[['ContinentId', 'Continent']],
    on='ContinentId',
    how='left'
)


In [74]:
master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52922 entries, 0 to 52921
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   TransactionId      52922 non-null  int64 
 1   UserId             52922 non-null  int64 
 2   VisitYear          52922 non-null  int64 
 3   VisitMonth         52922 non-null  int64 
 4   VisitModeId        52922 non-null  int64 
 5   AttractionId       52922 non-null  int64 
 6   Rating             52922 non-null  int64 
 7   ContinentId        52922 non-null  int64 
 8   RegionId           52922 non-null  int64 
 9   CountryId          52922 non-null  int64 
 10  CityId             52922 non-null  int64 
 11  VisitMode          52922 non-null  object
 12  AttractionCityId   52922 non-null  int64 
 13  AttractionTypeId   52922 non-null  int64 
 14  Attraction         52922 non-null  object
 15  AttractionAddress  52922 non-null  object
 16  AttractionType     52922 non-null  objec

In [75]:
master.shape

(52922, 21)

In [77]:
user_visits = master.groupby('UserId')['TransactionId'].count().reset_index()
user_visits.columns = ['UserId', 'TotalVisits']

master = master.merge(user_visits, on='UserId', how='left')


In [78]:
user_avg_rating = master.groupby('UserId')['Rating'].mean().reset_index()
user_avg_rating.columns = ['UserId', 'UserAvgRating']

master = master.merge(user_avg_rating, on='UserId', how='left')


In [79]:
attraction_popularity = master.groupby('AttractionId')['TransactionId'].count().reset_index()
attraction_popularity.columns = ['AttractionId', 'AttractionPopularity']

master = master.merge(attraction_popularity, on='AttractionId', how='left')


In [80]:
attraction_avg_rating = master.groupby('AttractionId')['Rating'].mean().reset_index()
attraction_avg_rating.columns = ['AttractionId', 'AttractionAvgRating']

master = master.merge(attraction_avg_rating, on='AttractionId', how='left')


In [81]:
master.shape


(52922, 25)

In [82]:
master.to_csv(r"C:\Users\kisho\Downloads\Tourism_Experience_Analytics_Project\Data\master_tourism_dataset.csv", index=False)
